### ISSUE TITLE
find-concepts?id=   replies/redirects in html rather rdf+xml

### ISSUE THREAD

**Issue by proycon** [OpenSKOS/OpenSKOS#64]
I don't know if this is an OpenSKOS problem, a problem with the installation at Meertens, or if I'm just misunderstanding the API: 

If I access for instance https://openskos.meertens.knaw.nl/ccr/api/find-concepts?id=http://hdl.handle.net/11459/CCR_C-4914_0de006d5-bd2d-1691-9bdf-fc7faed24d10 , I am redirected to a html page, I was expecting an rdf+xml response instead.

**Comment by olhsha** [comment]
The uri "https://openskos.meertens.knaw.nl/cc"r refers to OpenSKOS 1 production backend, which phasing out and not supported any more. This git-hub repo refers to OpenSKOS 2 backend, which is not in production yet and runs on test servers.  The Master branch runs on http://accept.openskos.beeldengeluid.nl.pictura-dp.nl/api/, for example http://accept.openskos.beeldengeluid.nl.pictura-dp.nl/api/find-concepts?q=*:*  . The branch "developMeertens" runs on http://145.100.58.79/ccr/public/api and http://145.100.58.79/clavas/public/api, check for instance
http://145.100.58.79/ccr/public/api/find-concepts?q=prefLabel:* and http://145.100.58.79/clavas/public/api/find-concepts?q=prefLabel:a* . 

Both branches of OpenSKOS 2 should output what you expect in your example, check for instance 45.100.58.79/clavas/public/api/find-concepts?id=http://openskos.meertens.knaw.nl/Organisations/12f5fef1-ad41-424e-ad24-55f545010d27

The Master branch is regularly merged into meertens branch. At the moment Meertens is waiting when a new super-speeding-up update by Picturae is pushed.

**Comment by proycon** [comment]
Thanks, so it'll be solved when production updates again, I'll play around on the development server for now to inspect stuff then, no problem.
